-- Add incident and timing fields to tickets table
ALTER TABLE public.tickets
ADD COLUMN IF NOT EXISTS incident_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS issue_start BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS detection_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS escalation_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS provider_notified_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS issue_cleared BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS restoration_time_confirmed TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS gross_downtime_min INTEGER,
ADD COLUMN IF NOT EXISTS provider_downtime_min INTEGER,
ADD COLUMN IF NOT EXISTS root_cause_lev1 TEXT,
ADD COLUMN IF NOT EXISTS root_cause_lev2 TEXT,
ADD COLUMN IF NOT EXISTS sla_impacted BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS redundancy_available BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS partner_impacted BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS rfo_received BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS preventive_action TEXT;

-- Add entity reference fields to tickets table
ALTER TABLE public.tickets
ADD COLUMN IF NOT EXISTS demarcation TEXT,
ADD COLUMN IF NOT EXISTS link_name TEXT,
ADD COLUMN IF NOT EXISTS site_id TEXT,
ADD COLUMN IF NOT EXISTS service_type TEXT,
ADD COLUMN IF NOT EXISTS detection_source TEXT,
ADD COLUMN IF NOT EXISTS traffic_impact TEXT;
